x<- pretty(c(-10,10),1000)
y1<- cos(x)
y2<- sin(x)
plot(x,y1,type="b",pch=19,col="red",xlab="x",ylab="y")
lines(x,y2,type="b",pch=19,col="blue")
legend("topleft",c("sin(x)","cos(x)"),fill=c("red","blue"))
dev.off()
x<- pretty(c(-3,3),1000)
y1<- dnorm(x)
y2<- dnorm(x,m=1,sd=0.8)
plot(x,y2,type="b",pch=20,col="red",xlab="z-scores",ylab="Density")
lines(x,y1,type="b",pch=19,col="blue")
legend("topleft",c("norm(0,1)","N(1,0.64)"),fill=c("blue","red"))
dev.off()
