# Use PHP 8.3 official image with Apache
FROM php:8.3-apache

# Install necessary PHP extensions for MySQL
RUN docker-php-ext-install mysqli

WORKDIR C:\Users\Zhu Jin Shun\Downloads\dockerized-web-app\src