version: "3.3"
services:
  web:
    container_name: php-web
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
    ports:
      - "80:80"
    build: ./php
    volumes:
      - ./src:/var/www/html

  mysql:
    container_name: mysql-db
    ports:
      - "3306:3306"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'mypassword'
    volumes:
      - ./db:/var/lib/mysql
